# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: '42 1 * * *'

name: save-cchecks

jobs:
  ccheks:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            ctv
            dplyr
            glue
            xml2
            purrr
            rvest

      - name: Gather data
        run: Rscript _scripts/cchecks.R

      - name: Save data
        if: github.event_name != 'pull_request'
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git log
          git add _data/*
          git commit -m 'New cchecks data'
          git push origin main
          echo "pushed to github"
